# prometheus-remote-auth-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: prometheus-remote-auth
  namespace: monitoring
type: Opaque
stringData:
  username: admin       # Basic Auth 用户名
  password: Plasoadmin123!  # Basic Auth 密码
  web-config.yaml: |
    basic_auth_users:
      admin: $2y$10$HhBRZbeIikOjuKWLNyUF5uHdt5CjI/QeLuzUrPUb0lGlo64xDhpl.
